#!/usr/bin/env bash
# Displays numbers 1 to 20, with special messages for 4, 9, and 17

i=0
while [ "$i" -lt 20 ]; do
	((i++))
	echo "$i"
	case "$i" in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
done
