#!/usr/bin/env bash
# Displays PID and process name of processes whose name contains 'bash'
# Cannot use ps

for pid_dir in /proc/[0-9]*/
do
    pid="${pid_dir//[^0-9]/}"
    comm_file="$pid_dir/comm"

    if [ -r "$comm_file" ]; then
        name=$(cat "$comm_file" 2>/dev/null)
        if [[ "$name" == *"bash"* ]]; then
            echo "$pid $name"
        fi
    fi
done
